language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 14tf55466q9f/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 14tf55466q9f/docker-react npm run test
